name: templette-markdown
version: 0.1.0
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

category: Text
synopsis: templette plugin for rendering Markdown templates
description: |
  templette plugin for rendering Markdown templates
  See templette's README for more information.

license: BSD3
license-file: LICENSE.md

github: brandonchinn178/templette

extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base < 5
    - containers < 0.7
    - templette < 1
    - text < 3

executable:
  main: exe/Main.hs
  dependencies:
    - base < 5
    - templette
    - templette-markdown
