name: templette-markdown
version: 0.1.0
category: Text
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
github: brandonchinn178/templette

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base < 5
    - containers
    - templette
    - text

executable:
  main: exe/Main.hs
  dependencies:
    - base < 5
    - templette
    - templette-markdown
