name: templette
version: 0.1.0
category: Text
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
github: brandonchinn178/templette

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wno-unused-packages

library:
  source-dirs: src
  dependencies:
    - base < 5
    - containers
    - megaparsec
    - mtl
    - text

executable:
  main: exe/Main.hs
  dependencies:
    - base < 5
    - templette

tests:
  templette-tests:
    source-dirs: test
    main: Main.hs
    build-tool-depends:
      - tasty-autocollect:tasty-autocollect
    ghc-options: -F -pgmF tasty-autocollect
    dependencies:
      - base
      - tasty
      - tasty-autocollect
      - tasty-hunit
      - templette
      - text
