name: templette
version: 0.1.0
category: Text
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
github: brandonchinn178/templette

extra-source-files:
  - test/goldens/**/*.golden

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base < 5
    - containers
    - hint
    - megaparsec
    - mtl
    - text
    - unliftio

executable:
  main: exe/Main.hs
  dependencies:
    - base < 5
    - templette

tests:
  templette-tests:
    source-dirs: test
    main: Main.hs
    build-tools:
      - tasty-autocollect:tasty-autocollect
    ghc-options: -F -pgmF tasty-autocollect
    dependencies:
      - base
      - bytestring
      - tasty
      - tasty-autocollect
      - tasty-golden
      - tasty-hunit
      - templette
      - text
